import turk from "./assets/turkhavayollari.png";
import pegasus from "./assets/Pegasus.png";
import anadolu from "./assets/anadolujet.png";
import sun from "./assets/anadolujet.png";

const data = [
  {
    id: 1,
    price: 2999,
    depart: "3/9/2023",
    arrival: "3/9/2023",
    departTime: "9:36 AM",
    arrivalTime: "9:01 AM",
    code: "TY-4545",
    flightImg: anadolu,
    from: {
      city: "Adana",
      short: "Adana Şakirpaşa Havalimanı (ADA)",
    },
    to: {
      city: "Amasya",
      short: "Merzifon Amasya Havalimanı (MZH)",
    },
  },
  {
    id: 2,
    price: 1433,
    depart: "3/9/2023",
    arrival: "3/9/2023",
    departTime: "3:37 AM",
    arrivalTime: "5:15 AM",
    code: "TY-6586",
    flightImg: pegasus,
    from: {
      city: "Adıyaman",
      short: "Adıyaman Havalimanı (ADF)",
    },
    to: {
      city: "Ankara",
      short: "Esenboğa Havalimanı (ESB)",
    },
  },
  {
    id: 3,
    price: 1025,
    depart: "3/9/2023",
    arrival: "3/9/2023",
    departTime: "11:49 AM",
    arrivalTime: "2:11 AM",
    code: "TY-4548",
    flightImg: turk,
    from: {
      city: "Afyonkarahisar",
      short: "Afyonkarahisar Zafer Havalimanı (AFY)",
    },
    to: {
      city: "Artvin",
      short: "Artvin Hopa Havalimanı (HOP)",
    },
  },
  {
    id: 4,
    price: 1102,
    depart: "3/9/2023",
    arrival: "3/9/2023",
    departTime: "3:26 AM",
    arrivalTime: "3:45 AM",
    code: "TY-4548",
    flightImg: turk,
    from: {
      city: "Ağrı",
      short: "Ağrı Ahmed-i Hani Havalimanı (AJI)",
    },
    to: {
      city: "Erzincan",
      short: "Erzincan Havalimanı (ERC)",
    },
  },
  {
    id: 5,
    price: 569,
    depart: "4/9/2023",
    arrival: "4/9/2023",
    departTime: "9:34 AM",
    arrivalTime: "4:14 AM",
    code: "TY-8895",
    flightImg: sun,
    from: {
      city: "Amasya",
      short: "Merzifon Amasya Havalimanı (MZH)",
    },
    to: {
      city: "Elazığ",
      short: "Elazığ Havalimanı (EZS)",
    },
  },
  {
    id: 6,
    price: 1058,
    depart: "5/9/2023",
    arrival: "5/9/2023",
    departTime: "1:09 AM",
    arrivalTime: "10:39 AM",
    code: "TY-6586",
    flightImg: sun,
    from: {
      city: "Ankara",
      short: "Esenboğa Havalimanı (ESB)",
    },
    to: {
      city: "Diyarbakır",
      short: "Diyarbakır Havalimanı (DIY)",
    },
  },
  {
    id: 7,
    price: 1929,
    depart: "5/9/2023",
    arrival: "5/9/2023",
    departTime: "9:43 AM",
    arrivalTime: "5:25 AM",
    code: "TY-4548",
    flightImg: turk,
    from: {
      city: "Antalya",
      short: "Antalya Havalimanı (AYT)",
    },
    to: {
      city: "Zonguldak",
      short: "Zonguldak Çaycuma Havalimanı (ONQ)",
    },
  },
  {
    id: 8,
    price: 2556,
    depart: "5/9/2023",
    arrival: "5/9/2023",
    departTime: "2:02 AM",
    arrivalTime: "12:05 AM",
    code: "TY-1245",
    flightImg: pegasus,
    from: {
      city: "Artvin",
      short: "Artvin Hopa Havalimanı (HOP)",
    },
    to: {
      city: "Bitlis",
      short: "Bitlis Havalimanı (BZI)",
    },
  },
  {
    id: 9,
    price: 2511,
    depart: "6/9/2023",
    arrival: "6/9/2023",
    departTime: "9:24 AM",
    arrivalTime: "3:04 AM",
    code: "TY-8895",
    flightImg: anadolu,
    from: {
      city: "Aydın",
      short: "Aydın Çıldır Havalimanı (ADF)",
    },
    to: {
      city: "Bingöl",
      short: "Bingöl Havalimanı (BGG)",
    },
  },
  {
    id: 10,
    price: 2706,
    depart: "6/9/2023",
    arrival: "6/9/2023",
    departTime: "7:01 AM",
    arrivalTime: "12:53 AM",
    code: "TY-5487",
    flightImg: anadolu,
    from: {
      city: "Balıkesir",
      short: "Balıkesir Koca Seyit Havalimanı (EDO)",
    },
    to: {
      city: "Bilecik",
      short: "Bilecik Havalimanı (BLC)",
    },
  },
  {
    id: 11,
    price: 1553,
    depart: "8/9/2023",
    arrival: "8/9/2023",
    departTime: "5:25 AM",
    arrivalTime: "4:15 AM",
    code: "TY-3332",
    flightImg: pegasus,
    from: {
      city: "Bilecik",
      short: "Bilecik Havalimanı (BLC)",
    },
    to: {
      city: "Balıkesir",
      short: "Balıkesir Koca Seyit Havalimanı (EDO)",
    },
  },
  {
    id: 12,
    price: 2090,
    depart: "8/9/2023",
    arrival: "8/9/2023",
    departTime: "3:23 AM",
    arrivalTime: "12:47 AM",
    code: "TY-4545",
    flightImg: anadolu,
    from: {
      city: "Bingöl",
      short: "Bingöl Havalimanı (BGG)",
    },
    to: {
      city: "Aydın",
      short: "Aydın Çıldır Havalimanı (ADF)",
    },
  },
  {
    id: 13,
    price: 500,
    depart: "8/9/2023",
    arrival: "8/9/2023",
    departTime: "1:55 AM",
    arrivalTime: "2:03 AM",
    code: "TY-1215",
    flightImg: turk,
    from: {
      city: "Bitlis",
      short: "Bitlis Havalimanı (BZI)",
    },
    to: {
      city: "Artvin",
      short: "Artvin Hopa Havalimanı (HOP)",
    },
  },
  {
    id: 14,
    price: 2257,
    depart: "9/9/2023",
    arrival: "9/9/2023",
    departTime: "10:37 AM",
    arrivalTime: "2:34 AM",
    code: "TY-5487",
    flightImg: pegasus,
    from: {
      city: "Zonguldak",
      short: "Zonguldak Çaycuma Havalimanı (ONQ)",
    },
    to: {
      city: "Antalya",
      short: "Antalya Havalimanı (AYT)",
    },
  },
  {
    id: 15,
    price: 2930,
    depart: "9/9/2023",
    arrival: "9/9/2023",
    departTime: "6:50 AM",
    arrivalTime: "2:47 AM",
    code: "TY-1245",
    flightImg: turk,
    from: {
      city: "Diyarbakır",
      short: "Diyarbakır Havalimanı (DIY)",
    },
    to: {
      city: "Ankara",
      short: "Esenboğa Havalimanı (ESB)",
    },
  },
  {
    id: 16,
    price: 2977,
    depart: "9/9/2023",
    arrival: "9/9/2023",
    departTime: "6:16 AM",
    arrivalTime: "9:28 AM",
    code: "TY-1245",
    flightImg: turk,
    from: {
      city: "Elazığ",
      short: "Elazığ Havalimanı (EZS)",
    },
    to: {
      city: "Amasya",
      short: "Merzifon Amasya Havalimanı (MZH)",
    },
  },
  {
    id: 17,
    price: 1544,
    depart: "9/9/2023",
    arrival: "9/9/2023",
    departTime: "7:44 AM",
    arrivalTime: "9:29 AM",
    code: "TY-4112",
    flightImg: sun,
    from: {
      city: "Erzincan",
      short: "Erzincan Havalimanı (ERC)",
    },
    to: {
      city: "Ağrı",
      short: "Ağrı Ahmed-i Hani Havalimanı (AJI)",
    },
  },
  {
    id: 18,
    price: 1242,
    depart: "11/9/2023",
    arrival: "11/9/2023",
    departTime: "5:15 AM",
    arrivalTime: "9:35 AM",
    code: "TY-1245",
    flightImg: turk,
    from: {
      city: "Erzurum",
      short: "Erzurum Havalimanı (ERZ)",
    },
    to: {
      city: "Adana",
      short: "Adana Şakirpaşa Havalimanı (ADA)",
    },
  },
  {
    id: 19,
    price: 1491,
    depart: "11/9/2023",
    arrival: "11/9/2023",
    departTime: "1:44 AM",
    arrivalTime: "11:47 AM",
    code: "TY-1215",
    flightImg: turk,
    from: {
      city: "Eskişehir",
      short: "Eskişehir Anadolu Havalimanı (AOE)",
    },
    to: {
      city: "Adıyaman",
      short: "Adıyaman Havalimanı (ADF)",
    },
  },
  {
    id: 20,
    price: 2488,
    depart: "11/9/2023",
    arrival: "11/9/2023",
    departTime: "8:45 AM",
    arrivalTime: "3:19 AM",
    code: "TY-1245",
    flightImg: pegasus,
    from: {
      city: "Gaziantep",
      short: "Gaziantep Oğuzeli Havalimanı (GZT)",
    },
    to: {
      city: "Afyonkarahisar",
      short: "Afyonkarahisar Zafer Havalimanı (AFY)",
    },
  },
];

export default data;
